version: "2"
services:
  webserver:
    image: mydemophpimage
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_DB_CONNECTION: mysql
      MYSQL_DB_NAME: bf3sgd9coetcbwmoanvr
      MYSQL_USER: u7m88jwogemd5bwx
      MYSQL_PASSWORD: JQVbDIOXA5f88eaqdpsF
      SITE_URL: bf3sgd9coetcbwmoanvr-mysql.services.clever-cloud.com
    networks:
      - test

networks:
  test:
    external: true